# -*- coding: utf-8 -*-
"""TNL6323 - Lab06 (TFIDF and Word2Vec).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXVwgKKi7Q6na3wUvuMdL5IrmHfQj1LA

To start, we’ll import the necessary libraries.
"""

import nltk

import pandas as pd

import math

"""In this article, we’ll be working with two simple documents containing one sentence each."""

documentA = 'the man went out for a walk'
documentB = 'the children sat around the fire'

"""Machine learning algorithms cannot work with raw text directly. Rather, the text must be converted into vectors of numbers.

In natural language processing, a common technique for extracting features from text is to place all of the words that occur in the text in a bucket. This aproach is called a bag of words model or BoW for short. It’s referred to as a “bag” of words because any information about the structure of the sentence is lost.
"""

bagOfWordsA = documentA.split(' ')
bagOfWordsB = documentB.split(' ')

print(bagOfWordsA, "\n")
print(bagOfWordsB)

"""By casting the bag of words to a set, we can automatically remove any duplicate words."""

uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB))

uniqueWords = sorted(uniqueWords)
print(uniqueWords)

"""Next, we’ll create a dictionary of words and their occurence for each document in the corpus (collection of documents)."""

numOfWordsA = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsA:
    numOfWordsA[word] += 1

numOfWordsB = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsB:
    numOfWordsB[word] += 1

print(numOfWordsA, "\n")
print(numOfWordsB)

"""Another problem with the bag of words approach is that it doesn’t account for noise. In other words, certain words are used to formulate sentences but do not add any semantic meaning to the text. For example, the most commonly used word in the english language is "the" which represents 7% of all words written or spoken. You couldn’t deduce anything about a text given the fact that it contains the word the. On the other hand, words like good and awesome could be used to determine whether a rating was positive or not.

Often times, when building a model with the goal of understanding text, you’ll see all of stop words being removed. Another strategy is to score the relative importance of words using TF-IDF.

**Term Frequency (TF)**

Term frequency refers to the number of times a word appears in a document. Every document has its own term frequency. The following code implements term frequency in python. The term frequency is always computed by the log base 10 of the term frequency + 1.
"""

import math

# TF(word) = log_10(word frequency + 1)

def computeTF(numOfWords):

    tfDict = {}

    for word, tf in numOfWords.items():
        tfDict[word] = math.log10(tf + 1)
    return tfDict

"""The following lines compute the term frequency for each of our documents."""

tfA = computeTF(numOfWordsA)
tfB = computeTF(numOfWordsB)

print(tfA,"\n")
print(tfB)

"""**Inverse Document Frequency (IDF)**

The log base 10 of the number of documents divided by the number of documents that contain the word w. Inverse data frequency determines the weight of rare words across all documents in the corpus. The following code implements inverse document frequency in python.
"""

# IDF(word) = log_10(N / document frequency of word)

def computeIDF(documents):
    N = len(documents)

    idfDict = dict.fromkeys(uniqueWords, 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1

    for word, df in idfDict.items():
        idfDict[word] = math.log10(N / float(df))
    return idfDict

"""The IDF is computed once for all documents."""

idfs = computeIDF([numOfWordsA, numOfWordsB])
print(idfs)

"""**Term Frequency Inverse Document Frequency (TF-IDF)**

Lastly, the TF-IDF is simply the TF multiplied by IDF.
"""

def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

"""Finally, we can compute the TF-IDF scores for all the words in the corpus."""

tfidfA = computeTFIDF(tfA, idfs)
tfidfB = computeTFIDF(tfB, idfs)

df = pd.DataFrame([tfidfA, tfidfB])

print(df)

"""**TF-IDF by sklearn**

Rather than manually implementing TF-IDF ourselves, we could use the TfidfVectorizer class provided by sklearn. The TfidfVectorizer class converts a collection of raw documents to a matrix of TF-IDF features.
"""

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

# return the tf-idf-weighted document-term matrix
# in compressed sparse row matrix where only nonzero values are stored
vectors = vectorizer.fit_transform([documentA, documentB])
print("vectors:\n", vectors)

# convert the sparse matrix to a dense matrix
dense = vectors.todense()
print("dense:\n", dense)

# get the words to be used as the column header
feature_names = vectorizer.get_feature_names_out()

# convert the tfidf to a 2-dimensional tabular data (dataframe)
tfidf_df_sklearn = pd.DataFrame(dense, columns=feature_names)

print(tfidf_df_sklearn)

"""**Word2Vec**

Word2Vec is an algorithm for constructing vector representations of words, also known as word embeddings. The vector for each word is a semantic description of how that word is used in context, so two words that are used similarly in text will get similar vector representations. Once you map words into vector space, you can then use vector math to find words that have similar semantics.

gensim provides a nice Python implementation of *Word2Vec* that works perfectly with NLTK corpora. The model takes a list of sentences, and each sentence is expected to be a list of words. This is exactly what is returned by the sents() method of NLTK corpus readers.

So let’s compare the semantics of a couple of words in a few different NLTK corpora:
"""

import nltk
nltk.download('movie_reviews')
nltk.download('punkt')

# wv essentially contains the mapping between words and embeddings
print("\nWords similar to money:", )

print("\nWords similar to great:", )

print("\nWords similar to company:", )

"""References:

https://towardsdatascience.com/natural-language-processing-feature-engineering-using-tf-idf-e8b9d00e7e76

https://streamhacker.com/2014/12/29/word2vec-nltk/
"""